// Mocks generated by Mockito 5.4.6 from annotations
// in coin_market_app/test/unit/features/exchanges/data/repositories_impl/exchange_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:coin_market_app/features/exchanges/data/datasources/exchange_local_datasource.dart'
    as _i6;
import 'package:coin_market_app/features/exchanges/data/datasources/exchange_remote_datasource.dart'
    as _i3;
import 'package:coin_market_app/features/exchanges/data/models/exchange_asset_model.dart'
    as _i5;
import 'package:coin_market_app/features/exchanges/data/models/exchange_info_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeExchangeInfoModel_0 extends _i1.SmartFake
    implements _i2.ExchangeInfoModel {
  _FakeExchangeInfoModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ExchangeRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockExchangeRemoteDataSource extends _i1.Mock
    implements _i3.ExchangeRemoteDataSource {
  MockExchangeRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.ExchangeAssetModel>> getExchangeAssets(int? exchangeId) =>
      (super.noSuchMethod(
            Invocation.method(#getExchangeAssets, [exchangeId]),
            returnValue: _i4.Future<List<_i5.ExchangeAssetModel>>.value(
              <_i5.ExchangeAssetModel>[],
            ),
          )
          as _i4.Future<List<_i5.ExchangeAssetModel>>);

  @override
  _i4.Future<_i2.ExchangeInfoModel> getExchangeInfo(int? exchangeId) =>
      (super.noSuchMethod(
            Invocation.method(#getExchangeInfo, [exchangeId]),
            returnValue: _i4.Future<_i2.ExchangeInfoModel>.value(
              _FakeExchangeInfoModel_0(
                this,
                Invocation.method(#getExchangeInfo, [exchangeId]),
              ),
            ),
          )
          as _i4.Future<_i2.ExchangeInfoModel>);
}

/// A class which mocks [ExchangeLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockExchangeLocalDataSource extends _i1.Mock
    implements _i6.ExchangeLocalDataSource {
  MockExchangeLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.ExchangeAssetModel>?> getCachedExchangeAssets(
    int? exchangeId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedExchangeAssets, [exchangeId]),
            returnValue: _i4.Future<List<_i5.ExchangeAssetModel>?>.value(),
          )
          as _i4.Future<List<_i5.ExchangeAssetModel>?>);

  @override
  _i4.Future<void> cacheExchangeAssets(
    int? exchangeId,
    List<_i5.ExchangeAssetModel>? assets,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cacheExchangeAssets, [exchangeId, assets]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> isDataFresh(int? exchangeId) =>
      (super.noSuchMethod(
            Invocation.method(#isDataFresh, [exchangeId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> clearCache(int? exchangeId) =>
      (super.noSuchMethod(
            Invocation.method(#clearCache, [exchangeId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
