// Mocks generated by Mockito 5.4.6 from annotations
// in coin_market_app/test/unit/features/exchanges/data/datasources/exchange_local_datasource_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:coin_market_app/features/exchanges/data/datasources/exchange_local_datasource.dart'
    as _i2;
import 'package:coin_market_app/features/exchanges/data/models/exchange_asset_model.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ExchangeLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockExchangeLocalDataSource extends _i1.Mock
    implements _i2.ExchangeLocalDataSource {
  MockExchangeLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.ExchangeAssetModel>?> getCachedExchangeAssets(
    int? exchangeId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedExchangeAssets, [exchangeId]),
            returnValue: _i3.Future<List<_i4.ExchangeAssetModel>?>.value(),
          )
          as _i3.Future<List<_i4.ExchangeAssetModel>?>);

  @override
  _i3.Future<void> cacheExchangeAssets(
    int? exchangeId,
    List<_i4.ExchangeAssetModel>? assets,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cacheExchangeAssets, [exchangeId, assets]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> isDataFresh(int? exchangeId) =>
      (super.noSuchMethod(
            Invocation.method(#isDataFresh, [exchangeId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> clearCache(int? exchangeId) =>
      (super.noSuchMethod(
            Invocation.method(#clearCache, [exchangeId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
