// Mocks generated by Mockito 5.4.6 from annotations
// in coin_market_app/test/unit/features/exchanges/data/datasources/exchange_remote_datasource_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:coin_market_app/core/api/custom_http_client.dart' as _i3;
import 'package:coin_market_app/core/api/http_client_adapter.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDuration_0 extends _i1.SmartFake implements Duration {
  _FakeDuration_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHttpResponse_1 extends _i1.SmartFake implements _i2.HttpResponse {
  _FakeHttpResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CustomHttpClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockCustomHttpClient extends _i1.Mock implements _i3.CustomHttpClient {
  MockCustomHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  Duration get timeout =>
      (super.noSuchMethod(
            Invocation.getter(#timeout),
            returnValue: _FakeDuration_0(this, Invocation.getter(#timeout)),
          )
          as Duration);

  @override
  _i5.Future<_i2.HttpResponse> get(
    String? endpoint, {
    Map<String, String>? headers,
    Map<String, dynamic>? queryParameters,
    Duration? timeout,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [endpoint],
              {
                #headers: headers,
                #queryParameters: queryParameters,
                #timeout: timeout,
              },
            ),
            returnValue: _i5.Future<_i2.HttpResponse>.value(
              _FakeHttpResponse_1(
                this,
                Invocation.method(
                  #get,
                  [endpoint],
                  {
                    #headers: headers,
                    #queryParameters: queryParameters,
                    #timeout: timeout,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.HttpResponse>);

  @override
  _i5.Future<_i2.HttpResponse> post(
    String? endpoint, {
    Map<String, dynamic>? body,
    Map<String, String>? headers,
    Map<String, dynamic>? queryParameters,
    Duration? timeout,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [endpoint],
              {
                #body: body,
                #headers: headers,
                #queryParameters: queryParameters,
                #timeout: timeout,
              },
            ),
            returnValue: _i5.Future<_i2.HttpResponse>.value(
              _FakeHttpResponse_1(
                this,
                Invocation.method(
                  #post,
                  [endpoint],
                  {
                    #body: body,
                    #headers: headers,
                    #queryParameters: queryParameters,
                    #timeout: timeout,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.HttpResponse>);

  @override
  _i5.Future<_i2.HttpResponse> put(
    String? endpoint, {
    Map<String, dynamic>? body,
    Map<String, String>? headers,
    Map<String, dynamic>? queryParameters,
    Duration? timeout,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [endpoint],
              {
                #body: body,
                #headers: headers,
                #queryParameters: queryParameters,
                #timeout: timeout,
              },
            ),
            returnValue: _i5.Future<_i2.HttpResponse>.value(
              _FakeHttpResponse_1(
                this,
                Invocation.method(
                  #put,
                  [endpoint],
                  {
                    #body: body,
                    #headers: headers,
                    #queryParameters: queryParameters,
                    #timeout: timeout,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.HttpResponse>);

  @override
  _i5.Future<_i2.HttpResponse> delete(
    String? endpoint, {
    Map<String, String>? headers,
    Map<String, dynamic>? queryParameters,
    Duration? timeout,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [endpoint],
              {
                #headers: headers,
                #queryParameters: queryParameters,
                #timeout: timeout,
              },
            ),
            returnValue: _i5.Future<_i2.HttpResponse>.value(
              _FakeHttpResponse_1(
                this,
                Invocation.method(
                  #delete,
                  [endpoint],
                  {
                    #headers: headers,
                    #queryParameters: queryParameters,
                    #timeout: timeout,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.HttpResponse>);

  @override
  _i5.Future<_i2.HttpResponse> patch(
    String? endpoint, {
    Map<String, dynamic>? body,
    Map<String, String>? headers,
    Map<String, dynamic>? queryParameters,
    Duration? timeout,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [endpoint],
              {
                #body: body,
                #headers: headers,
                #queryParameters: queryParameters,
                #timeout: timeout,
              },
            ),
            returnValue: _i5.Future<_i2.HttpResponse>.value(
              _FakeHttpResponse_1(
                this,
                Invocation.method(
                  #patch,
                  [endpoint],
                  {
                    #body: body,
                    #headers: headers,
                    #queryParameters: queryParameters,
                    #timeout: timeout,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.HttpResponse>);
}
